before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      fTerm_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: fterm 
    homepage: https://github.com/bedirhangull/fterm
    repository:
      owner: bedirhangull
      name: homebrew-fterm
      branch: main
      token: "{{ .Env.PUBLISHER_TOKEN }}"
    description: fTerm is a CLI tool for managing shortcuts.
    commit_author:
      name: bedirhangull
      email: bedirhangul@bedirhangul.com
    license: MIT
    install: |
      bin.install "fterm"

checksum:
  name_template: "checksums.txt"
