# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fterm < Formula
  desc "fTerm is a CLI tool for managing shortcuts."
  homepage "https://github.com/bedirhangull/fterm"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bedirhangull/fTerm/releases/download/v1.2.0/fTerm_Darwin_x86_64.tar.gz"
      sha256 "fa49870e174cffcf713d2c9b7c879475d5c5b9eae29309711161f56d26e79294"

      def install
        bin.install "fterm"
      end
    end
    on_arm do
      url "https://github.com/bedirhangull/fTerm/releases/download/v1.2.0/fTerm_Darwin_arm64.tar.gz"
      sha256 "aa376f35a42cc698b57e052473a4d1c59dc85a2ab904b93a0c504ef2bb2d1d18"

      def install
        bin.install "fterm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bedirhangull/fTerm/releases/download/v1.2.0/fTerm_Linux_x86_64.tar.gz"
        sha256 "2778d8bef79265ff60d1f394eefdba52cfef83db946b43af9559807189ee1c5e"

        def install
          bin.install "fterm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bedirhangull/fTerm/releases/download/v1.2.0/fTerm_Linux_arm64.tar.gz"
        sha256 "c1e30ad5cf31af60b7af70476b8300427d63a213638bca4b44969a4cda49a54c"

        def install
          bin.install "fterm"
        end
      end
    end
  end
end
